In [102]:
import torch
import torch.nn.functional as F
import numpy as np

In [115]:
BATCH_SIZE = 2
NUM_DAYS = 3

In [116]:
mask = np.random.choice([0, 1], (BATCH_SIZE, NUM_DAYS))
mask = torch.tensor(mask)
mask

tensor([[1, 1, 1],
        [1, 1, 0]])

In [117]:
score = torch.rand(BATCH_SIZE, NUM_DAYS, NUM_DAYS)
score

tensor([[[0.7422, 0.3328, 0.7123],
         [0.0321, 0.9112, 0.9730],
         [0.9703, 0.1360, 0.7599]],

        [[0.9046, 0.7782, 0.7288],
         [0.5297, 0.7126, 0.9078],
         [0.0425, 0.3255, 0.9714]]])

In [118]:
extended_mask = mask.repeat(1, 1, NUM_DAYS).reshape(BATCH_SIZE, NUM_DAYS, NUM_DAYS)
extended_mask

tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 0],
         [1, 1, 0],
         [1, 1, 0]]])

In [119]:
score[extended_mask == 0] = -np.inf
score

tensor([[[0.7422, 0.3328, 0.7123],
         [0.0321, 0.9112, 0.9730],
         [0.9703, 0.1360, 0.7599]],

        [[0.9046, 0.7782,   -inf],
         [0.5297, 0.7126,   -inf],
         [0.0425, 0.3255,   -inf]]])

In [120]:
attention = F.softmax(score, dim=-1)
attention

tensor([[[0.3796, 0.2520, 0.3684],
         [0.1675, 0.4034, 0.4291],
         [0.4455, 0.1934, 0.3610]],

        [[0.5316, 0.4684, 0.0000],
         [0.4544, 0.5456, 0.0000],
         [0.4297, 0.5703, 0.0000]]])