In [1]:
import torch
import numpy as np

In [64]:
BATCH_SIZE = 2
NUM_DAYS = 3

mask = torch.tensor(np.random.choice([0, 1], (BATCH_SIZE, NUM_DAYS)))
score = torch.rand(BATCH_SIZE, NUM_DAYS, NUM_DAYS)

mask = torch.ones(BATCH_SIZE, NUM_DAYS)
mask[0, 0] = 0
mask[1, 2] = 0

score[mask == 0] = -np.inf
attention = torch.softmax(score, dim=-1)

In [65]:
mask = torch.ones(BATCH_SIZE, NUM_DAYS)
mask[:, 0] = 0
mask[:, 2] = 0
mask

tensor([[0., 1., 0.],
        [0., 1., 0.]])

In [62]:
expanded_mask.shape

torch.Size([2, 3, 1])

In [63]:
expanded_mask = mask[:, :, None]
score[mask == 0] = -np.inf
attention = torch.softmax(score, dim=-1)

IndexError: The shape of the mask [2, 3, 1] at index 2 does not match the shape of the indexed tensor [2, 3, 3] at index 2

In [56]:
score

tensor([[[  -inf,   -inf,   -inf],
         [0.5273, 0.9908, 0.1168],
         [0.9023, 0.9709, 0.2129]],

        [[0.5984, 0.6284, 0.9256],
         [0.2813, 0.8023, 0.2634],
         [  -inf,   -inf,   -inf]]])

In [27]:
attention

tensor([[[0.0000, 0.3022, 0.1326, 0.2944, 0.2708],
         [0.0000, 0.1545, 0.3585, 0.1678, 0.3191],
         [0.0000, 0.1897, 0.2285, 0.2377, 0.3441],
         [0.0000, 0.3188, 0.1961, 0.3439, 0.1412],
         [0.0000, 0.3649, 0.3072, 0.1611, 0.1668]]])